### ISSUE TITLE
websocket has no attribute 'enabletrace'

### ISSUE THREAD

**Issue by AndreasMoe** [oysteoh/tibber-pypulse-ws#1]
Hi, Start of by saying that I am not python experienced :)
I try to run the code in pycharm, installed modules: websocket, ssl, json in pycharm
When I run the code with my token, I get
"    websocket.enableTrace(True)
AttributeError: module 'websocket' has no attribute 'enableTrace'"

Is this the wrong websocket module?
![image](https://user-images.githubusercontent.com/43982077/67471331-807c7480-f64f-11e9-9ce4-53f0c075f45d.png)
If so, where can I get correct modules?

**Comment by AndreasMoe** [comment]
Found that adding websocket-client fixed the above error

**Comment by oysteoh** [comment]
i will give it a go making this lib more useful since there is a couple of people which have started using it... will make it pip installable with all deps and we could avoid this. feel free to add feature - requests if you have any ! :-)
